### ISSUE TITLE
Can we get the rest of the source?

### ISSUE THREAD

**Issue by PapaCharlie** [MrPing/Flamite#19]
I was wondering if we could get the rest of the Ember source, like the template files and whatnot. I wanted to implement automatic messaging, among other things. If I manage to get anything cool done, I'll submit a pull request

**Comment by KLVN** [comment]
+1

**Comment by tomlandia** [comment]
I don't know what's going on with the last 3 commits but you can [come back before](https://github.com/MrPing/Flamite/tree/08e593cd89ec8b2cc1b8f6e538bfde6670817a48) or look up (my fork)[https://github.com/tomlandia/Flamite] (no analytics and fake location).

**Comment by davidfurlong** [comment]
Reopen!!
